package com.bizfns.services.Repository;

import com.bizfns.services.Entity.CompanyMasterEntity;
import org.json.simple.JSONObject;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import javax.transaction.Transactional;
import java.util.List;

@Repository

public interface RegistrationRepository extends JpaRepository<CompanyMasterEntity, Long> {



    @Transactional
    @Query(value = "INSERT INTO \"Bizfns\".\"COMPANY_MASTER\"(\n" +
            "    \"BUSINESS_NAME\",\n" +
            "    \"COMPANY_BACKUP_EMAIL\",\n" +
            "    \"COMPANY_CREATED_AT\",\n" +
            "    \"CLIENT_ID\",\n" +
            "    \"SCHEMA_ID\",\n" +
            "    \"COMISSION_RATE\",\n" +
            "    \"COMPANY_BACKUP_PHONE_NUMBER\",\n" +
            "    \"COMPANY_STATUS\",\n" +
            "    \"PASSWORD\"\n" +
            ") \n" +
            "VALUES (\n" +
            "    :businessName,\n" +
            "    :businessEmail,\n" +
            "    CURRENT_TIMESTAMP,\n" +
            "    :encryptedClientId,\n" +
            "    :tenantId,\n" +
            "    10,\n" +
            "    :phoneNumber,\n" +
            "    'ACTIVE',\n" +
            "    :password\n" +
            ") returning \"COMPANY_ID\"", nativeQuery = true)
    Integer inserCompanyRegistrationData(String businessName, String phoneNumber,
           String businessEmail, String password, String tenantId, String encryptedClientId);



    @Modifying
    @Transactional
    @Query(value = "INSERT INTO \"Bizfns\".\"COMPANY_SUBSCRIPTION\"(\n" +
            "    \"FK_COMPANY_BUSINESS_MAPPING_ID\",\n" +
            "    \"FK_SUBSCRIPTION_PLAN_ID\",\n" +
            "    \"COMPANY_SUBSCRIPTION_START_DATE\",\n" +
            "    \"COMPANY_SUBSCRIPTION_END_DATE\"\n" +
            ") VALUES (\n" +
            "    :autoGeneratedBusinessTypeIdId,\n" +
            "    :planId,\n" +
            "    CURRENT_DATE,\n" +
            "    CURRENT_DATE + (SELECT \"SUBSCRIPTION_DURATION\" FROM \"Bizfns\".\"SUBSCRIPTION_PLAN_MASTER\" WHERE \"PK_SUBSCRIPTION_PLAN_ID\" = :planId) * INTERVAL '1 month'\n" +
            ")\n", nativeQuery = true)
    void insertCompanyRegistrationPlanData(Integer planId, Integer autoGeneratedBusinessTypeIdId);
    @Query(value = "select \"COMPANY_BACKUP_EMAIL\"  from  \"Bizfns\".\"COMPANY_MASTER\" where \"COMPANY_BACKUP_EMAIL\" = :businessEmail", nativeQuery = true)
    List<String> fetchUserIdByEmail(String businessEmail);

    @Query(value = "select \"BUSINESS_NAME\"  from  \"Bizfns\".\"COMPANY_MASTER\" where \"BUSINESS_NAME\" = :businessName", nativeQuery = true)
    List<String> fetchBusinessName(String businessName);
    @Query(value = "select \"COMPANY_BACKUP_PHONE_NUMBER\"  from  \"Bizfns\".\"COMPANY_MASTER\" where \"COMPANY_BACKUP_PHONE_NUMBER\" = :phoneNumber", nativeQuery = true)
    List<String> fetchUserIdByPhNo(String phoneNumber);

    @Query(value = " SELECT\n" +
            "   \"MOBILE_NUMBER\"\n" +
            "FROM\n" +
            "    \"Bizfns\".\"USER_MASTER\"\n" +
            "WHERE\n" +
            "    \"BUSINESS_NAME\" = :businessName ;", nativeQuery = true)
    List<String> fetchPhoneNumberOfBusiness(String businessName);

    @Query(value = " SELECT\n" +
            "   \"MOBILE_NUMBER\"\n" +
            "FROM\n" +
            "    \"Bizfns\".\"USER_MASTER\"\n" +
            "WHERE\n" +
            "    \"MOBILE_NUMBER\" = :phoneNumber ;", nativeQuery = true)
    List<String> fetchPrevAssoBuss(String phoneNumber);




    @Transactional
    @Query(value = "insert into \"Bizfns\".\"COMPANY_BUSINESS_TYPE_MAPPING\"\n" +
            "(\"FK_BUSINESS_TYPE_ID\",\n" +
            "\"FK_COMPANY_ID\",\n" +
            "\"BUSINESS_MAPPING_STATUS\") values(:businessType, :autoGeneratedCompId, 'active') returning \"PK_COMPANY_BUSINESS_MAPPING_ID\"\n", nativeQuery = true)
    Integer inserCompanyRegistrationBusinessTypeData(Integer businessType, Integer autoGeneratedCompId);


    @Modifying
    @Transactional
    @Query(value = "insert into \"Bizfns\".\"USER_MASTER\" (\n" +
            "\"EMAIL_ID\",\n" +
            "\"MOBILE_NUMBER\",\n" +
            "\"SCHEMA_NAME\",\n" +
            "\"BUSINESS_NAME\",\n" +
            "\"USER_TYPE\",\n" +
            "\"CREATED_BY\",\n" +
            "\"UPDATED_BY\",\n" +
            "\"STATUS\") values (:businessEmail, :phoneNumber, :tenantId, :businessName, :userType, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVE')", nativeQuery = true)
    void insertBusinessIdData(String phoneNumber, String businessEmail, String businessName, String tenantId, String userType);
}
